#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : kmod
Version  : 26
Release  : 39
URL      : https://www.kernel.org/pub/linux/utils/kernel/kmod/kmod-26.tar.xz
Source0  : https://www.kernel.org/pub/linux/utils/kernel/kmod/kmod-26.tar.xz
Summary  : Library to deal with kernel modules
Group    : Development/Tools
License  : GPL-2.0 GPL-2.0+ LGPL-2.1
Requires: kmod-bin = %{version}-%{release}
Requires: kmod-data = %{version}-%{release}
Requires: kmod-lib = %{version}-%{release}
Requires: kmod-license = %{version}-%{release}
Requires: kmod-man = %{version}-%{release}
BuildRequires : docbook-xml
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : git
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
BuildRequires : gtk-doc
BuildRequires : gtk-doc-dev
BuildRequires : pkg-config
BuildRequires : pkgconfig(32liblzma)
BuildRequires : pkgconfig(32openssl)
BuildRequires : pkgconfig(32zlib)
BuildRequires : pkgconfig(liblzma)
BuildRequires : pkgconfig(openssl)
BuildRequires : pkgconfig(zlib)
BuildRequires : python-dev
BuildRequires : sed

%description
kmod - Linux kernel module handling
Information
===========
Build Status:
https://lucasdemarchi.semaphoreci.com/projects/kmod

%package bin
Summary: bin components for the kmod package.
Group: Binaries
Requires: kmod-data = %{version}-%{release}
Requires: kmod-license = %{version}-%{release}
Requires: kmod-man = %{version}-%{release}

%description bin
bin components for the kmod package.


%package data
Summary: data components for the kmod package.
Group: Data

%description data
data components for the kmod package.


%package dev
Summary: dev components for the kmod package.
Group: Development
Requires: kmod-lib = %{version}-%{release}
Requires: kmod-bin = %{version}-%{release}
Requires: kmod-data = %{version}-%{release}
Provides: kmod-devel = %{version}-%{release}

%description dev
dev components for the kmod package.


%package dev32
Summary: dev32 components for the kmod package.
Group: Default
Requires: kmod-lib32 = %{version}-%{release}
Requires: kmod-bin = %{version}-%{release}
Requires: kmod-data = %{version}-%{release}
Requires: kmod-dev = %{version}-%{release}

%description dev32
dev32 components for the kmod package.


%package lib
Summary: lib components for the kmod package.
Group: Libraries
Requires: kmod-data = %{version}-%{release}
Requires: kmod-license = %{version}-%{release}

%description lib
lib components for the kmod package.


%package lib32
Summary: lib32 components for the kmod package.
Group: Default
Requires: kmod-data = %{version}-%{release}
Requires: kmod-license = %{version}-%{release}

%description lib32
lib32 components for the kmod package.


%package license
Summary: license components for the kmod package.
Group: Default

%description license
license components for the kmod package.


%package man
Summary: man components for the kmod package.
Group: Default

%description man
man components for the kmod package.


%prep
%setup -q -n kmod-26
pushd ..
cp -a kmod-26 build32
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1549579819
unset LD_AS_NEEDED
export CFLAGS="$CFLAGS -Os -fdata-sections -ffunction-sections -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -Os -fdata-sections -ffunction-sections -fno-semantic-interposition "
export FFLAGS="$CFLAGS -Os -fdata-sections -ffunction-sections -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -Os -fdata-sections -ffunction-sections -fno-semantic-interposition "
%configure --disable-static --enable-tools --disable-test-modules
make  %{?_smp_mflags} LIBS=-lpthread

pushd ../build32/
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig"
export ASFLAGS="${ASFLAGS}${ASFLAGS:+ }--32"
export CFLAGS="${CFLAGS}${CFLAGS:+ }-m32"
export CXXFLAGS="${CXXFLAGS}${CXXFLAGS:+ }-m32"
export LDFLAGS="${LDFLAGS}${LDFLAGS:+ }-m32"
%configure --disable-static --enable-tools --disable-test-modules   --libdir=/usr/lib32 --build=i686-generic-linux-gnu --host=i686-generic-linux-gnu --target=i686-clr-linux-gnu
make  %{?_smp_mflags} LIBS=-lpthread
popd
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check
cd ../build32;
make VERBOSE=1 V=1 %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1549579819
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/kmod
cp COPYING %{buildroot}/usr/share/package-licenses/kmod/COPYING
cp libkmod/COPYING %{buildroot}/usr/share/package-licenses/kmod/libkmod_COPYING
cp testsuite/COPYING %{buildroot}/usr/share/package-licenses/kmod/testsuite_COPYING
cp tools/COPYING %{buildroot}/usr/share/package-licenses/kmod/tools_COPYING
pushd ../build32/
%make_install32
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
%make_install
## install_append content
ln -s kmod %{buildroot}/usr/bin/depmod
ln -s kmod %{buildroot}/usr/bin/insmod
ln -s kmod %{buildroot}/usr/bin/lsmod
ln -s kmod %{buildroot}/usr/bin/modinfo
ln -s kmod %{buildroot}/usr/bin/modprobe
ln -s kmod %{buildroot}/usr/bin/rmmod
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/depmod
/usr/bin/insmod
/usr/bin/kmod
/usr/bin/lsmod
/usr/bin/modinfo
/usr/bin/modprobe
/usr/bin/rmmod

%files data
%defattr(-,root,root,-)
/usr/share/bash-completion/completions/kmod

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/libkmod.so
/usr/lib64/pkgconfig/libkmod.pc

%files dev32
%defattr(-,root,root,-)
/usr/lib32/libkmod.so
/usr/lib32/pkgconfig/32libkmod.pc
/usr/lib32/pkgconfig/libkmod.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libkmod.so.2
/usr/lib64/libkmod.so.2.3.4

%files lib32
%defattr(-,root,root,-)
/usr/lib32/libkmod.so.2
/usr/lib32/libkmod.so.2.3.4

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/kmod/COPYING
/usr/share/package-licenses/kmod/libkmod_COPYING
/usr/share/package-licenses/kmod/testsuite_COPYING
/usr/share/package-licenses/kmod/tools_COPYING

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man5/depmod.d.5
/usr/share/man/man5/modprobe.d.5
/usr/share/man/man5/modules.dep.5
/usr/share/man/man5/modules.dep.bin.5
/usr/share/man/man8/depmod.8
/usr/share/man/man8/insmod.8
/usr/share/man/man8/kmod.8
/usr/share/man/man8/lsmod.8
/usr/share/man/man8/modinfo.8
/usr/share/man/man8/modprobe.8
/usr/share/man/man8/rmmod.8
